REM
REM DROP INDEXES
REM
DROP INDEX i_route_id;
DROP INDEX i_stop_id;
REM
REM CREATE INDEXES
REM
CREATE INDEX i_route_id ON VEHICLES_DATA_HISTORY(route_id);
CREATE INDEX i_stop_id ON VEHICLES_DATA_HISTORY(stop_id);
